### ISSUE TITLE
Lab #1 checkpoint listing

### ISSUE THREAD

**Issue by ppot** [gti525/e17-banque-1#3]
## Tasks list for lab1

- [x] Diagrammes de flot d’écrans 
- [x] Documentation des pages Web
- [x] Interfaces de services Web REST 
- [x] Cas d'utilisation
- [x] Diagramme de cas d'utilisation
- [x] Discussion
- [x] Introduction/conclusion/qualité du rapport
- [x] Prototype statique (qualité, ergonomie et structure)
